#!/bin/bash

if [[ -f /config/radarr/config.xml ]]; then
    PORT=$(xmlstarlet sel -T -t -v /Config/Port /config/radarr/config.xml)
fi

if [[ $(curl -sL "http://localhost:${PORT:-7878}/ping" | jq -r '.status' 2>/dev/null) = "OK" ]]; then
    exit 0
else
    exit 1
fi
