name: Build Image On Release

on:
  workflow_dispatch:
  release:
    types: [ published ]
  pull_request:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-split-image.yml@v8
    with:
      repo_owner: thespad
      app_name: "arr-in-one"
      release_type: "script"
      dockerhub_user: "thespad"
      target-arch: >-
        ["amd64", "aarch64"]
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
