#!/usr/bin/with-contenv bash

# Toggle services off
if [[ "${SONARR}" == "false" ]]; then
    touch /etc/services.d/sonarr/down
fi

if [[ "${RADARR}" == "false" ]]; then
    touch /etc/services.d/radarr/down
fi

if [[ "${LIDARR}" == "false" ]]; then
    touch /etc/services.d/lidarr/down
fi

if [[ "${READARR}" == "false" ]]; then
    touch /etc/services.d/readarr/down
fi

if [[ "${PROWLARR}" == "false" ]]; then
    touch /etc/services.d/prowlarr/down
fi

if [[ "${WHISPARR}" == "false" ]]; then
    touch /etc/services.d/whisparr/down
fi

# permissions
chown -R abc:abc \
    /config
